Create Table customer (
customer_id int,
first_name text,
last_name text,
company	text,
address	text,
city	text,
state text,
country	text,
postal_code text,
phone text,
fax text ,
email text,
support_rep_id int ,
primary key (customer_id));
